- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is username ?
    course: Devops
    private: false
  
  tasks:
  - name: Print details
    ansible.builtin.debug:
      msg: "username is {{ username }}"

  



